### ISSUE TITLE
Hobbylos

### ISSUE THREAD

**Issue by greg6775** [EinfachMc/GameJump-lernt-coden#4]
Habt ihr nichts besseres zu tun als irgendwelche hobbylose repositories zu erstellen?!?!? Ihr keks

**Comment by LeeDJD** [comment]
Idiot

**Comment by LeeDJD** [comment]
DANKE ICH DARF DES NETMA SCHLIE?EN WEIL ALEX ZU BLÖD IS WAU

**Comment by LeeDJD** [comment]
@EinfachAlex du idiot hallo

**Comment by EinfachAlex** [comment]
Frag doch GameJump

**Comment by greg6775** [comment]
ja @LeeDJD
